"use client";

import QuizTemplate, {
  type Question,
} from "@/components/Quiz/QuizTemplate";

const questions: Question[] = [
  {
    id: 1,
    question: "Super Prompt là gì?",
    questionEn: "What is a Super Prompt?",
    options: [
      "Prompt viết bằng tiếng Anh cho chính xác hơn",
      "Gom nhiều bước (multi-step) vào 1 prompt duy nhất có cấu trúc",
      "Prompt dài hơn 1000 từ",
      "Prompt được AI tự động tạo ra",
    ],
    optionsEn: [
      "A prompt written in English for better accuracy",
      "Combining multiple steps (multi-step) into a single structured prompt",
      "A prompt longer than 1000 words",
      "A prompt automatically generated by AI",
    ],
    correct: 1,
    explanation:
      "Super Prompt = gom nhiều bước vào 1 prompt có cấu trúc (Role + Steps + Rules + Format). Thuật ngữ của Bruce — không phải thuật ngữ chuẩn ngành.",
    explanationEn:
      "Super Prompt = combining multiple steps into one structured prompt (Role + Steps + Rules + Format). This is Bruce's terminology — not an industry-standard term.",
  },
  {
    id: 2,
    question: "Cấu trúc Super Prompt gồm những thành phần nào?",
    questionEn: "What are the components of a Super Prompt structure?",
    options: [
      "Input, Output, Model, API",
      "Role, Context, Steps, Rules, Format",
      "Câu hỏi, Trả lời, Kiểm tra",
      "Task, Context, Examples, Format",
    ],
    optionsEn: [
      "Input, Output, Model, API",
      "Role, Context, Steps, Rules, Format",
      "Question, Answer, Review",
      "Task, Context, Examples, Format",
    ],
    correct: 1,
    explanation:
      "Super Prompt có 5 phần: Role (vai trò) + Context (bối cảnh) + Steps (các bước) + Rules (ràng buộc) + Format (định dạng output).",
    explanationEn:
      "A Super Prompt has 5 parts: Role + Context + Steps + Rules + Format (output format).",
  },
  {
    id: 3,
    question: "Super Prompt khác Multi-step Prompting ở điểm nào?",
    questionEn: "How does a Super Prompt differ from Multi-step Prompting?",
    options: [
      "Super Prompt dùng tiếng Anh, Multi-step dùng tiếng Việt",
      "Multi-step hỏi từng bước riêng lẻ, Super Prompt gom tất cả vào 1 prompt",
      "Super Prompt chỉ dùng cho ChatGPT, Multi-step dùng cho Claude",
      "Không khác, chỉ là hai tên gọi",
    ],
    optionsEn: [
      "Super Prompt uses English, Multi-step uses Vietnamese",
      "Multi-step asks each step separately, Super Prompt combines everything into one prompt",
      "Super Prompt only works on ChatGPT, Multi-step works on Claude",
      "No difference, just two names for the same thing",
    ],
    correct: 1,
    explanation:
      "Multi-step: hỏi 3 lần, chờ 3 lần, copy-paste 3 lần. Super Prompt: paste 1 lần, AI tự chạy tuần tự từ đầu đến cuối. Cùng kết quả nhưng tiết kiệm thời gian + tái sử dụng được.",
    explanationEn:
      "Multi-step: ask 3 times, wait 3 times, copy-paste 3 times. Super Prompt: paste once, AI runs sequentially from start to finish. Same result but saves time and is reusable.",
  },
  {
    id: 4,
    question: "Khi nào KHÔNG nên dùng Super Prompt?",
    questionEn: "When should you NOT use a Super Prompt?",
    options: [
      "Khi task lặp đi lặp lại nhiều lần",
      "Khi cần chia sẻ prompt cho team dùng chung",
      "Khi cần kiểm tra kết quả giữa chừng trước khi làm bước tiếp",
      "Khi task có nhiều bước rõ ràng",
    ],
    optionsEn: [
      "When the task repeats many times",
      "When you need to share the prompt with your team",
      "When you need to review intermediate results before proceeding to the next step",
      "When the task has many clear steps",
    ],
    correct: 2,
    explanation:
      "Nếu output bước 1 nhạy cảm và cần bạn kiểm tra trước khi AI làm tiếp, thì Multi-step an toàn hơn. Super Prompt chạy 1 mạch — bạn không can thiệp giữa chừng được.",
    explanationEn:
      "If step 1's output is sensitive and you need to review it before AI continues, Multi-step is safer. Super Prompt runs straight through — you can't intervene midway.",
  },
  {
    id: 5,
    question: "Meta Prompt là gì?",
    questionEn: "What is a Meta Prompt?",
    options: [
      "Prompt viết bằng ngôn ngữ lập trình",
      "Prompt dùng để tạo ra prompt — AI hỏi lại bạn rồi tạo prompt hoàn chỉnh",
      "Prompt được mã hóa để bảo mật",
      "Prompt dài nhất có thể viết",
    ],
    optionsEn: [
      "A prompt written in a programming language",
      "A prompt used to create prompts — AI asks you questions then generates a complete prompt",
      "An encrypted prompt for security",
      "The longest prompt you can write",
    ],
    correct: 1,
    explanation:
      "Meta Prompt = bạn mô tả yêu cầu thô → AI hỏi 3-5 câu để hiểu rõ → AI tạo prompt hoàn chỉnh cho bạn copy & dùng. Giống đến bác sĩ: nói triệu chứng → bác sĩ hỏi thêm → kê đơn chuẩn.",
    explanationEn:
      "Meta Prompt = you describe a rough requirement, AI asks 3-5 clarifying questions, then AI generates a complete prompt for you to copy and use. Like visiting a doctor: describe symptoms, doctor asks follow-ups, then prescribes accurately.",
  },
  {
    id: 6,
    question: "Câu nào đúng về Meta Prompt?",
    questionEn: "Which statement about Meta Prompt is correct?",
    options: [
      "Bắt buộc phải dùng Meta Prompt mới có prompt tốt",
      "Meta Prompt giống \"bánh xe phụ\" — tốt để học, nhưng đích là tự viết được",
      "Meta Prompt chỉ hoạt động trên ChatGPT",
      "Meta Prompt thay thế hoàn toàn việc học Prompt Engineering",
    ],
    optionsEn: [
      "You must use Meta Prompt to get a good prompt",
      "Meta Prompt is like \"training wheels\" — great for learning, but the goal is to write prompts yourself",
      "Meta Prompt only works on ChatGPT",
      "Meta Prompt completely replaces learning Prompt Engineering",
    ],
    correct: 1,
    explanation:
      "Meta Prompt hữu ích cho người mới — giúp học cách viết prompt tốt. Sau 1-2 tuần, bạn sẽ tự viết được mà không cần AI hỏi lại nữa. Bánh xe phụ — học xong thì tháo ra!",
    explanationEn:
      "Meta Prompt is useful for beginners — it helps you learn how to write good prompts. After 1-2 weeks, you'll be able to write them yourself without AI asking clarifying questions. Training wheels — once you've learned, take them off!",
  },
  {
    id: 7,
    question: "Chatbot và AI Agent khác nhau cốt lõi ở điểm nào?",
    questionEn: "What is the core difference between a Chatbot and an AI Agent?",
    options: [
      "Chatbot miễn phí, Agent trả phí",
      "Chatbot xử lý 1 turn rồi dừng, Agent loop cho đến khi đạt mục tiêu",
      "Chatbot dùng tiếng Việt, Agent dùng tiếng Anh",
      "Chatbot là phần mềm cũ, Agent là phần mềm mới",
    ],
    optionsEn: [
      "Chatbots are free, Agents are paid",
      "Chatbots handle one turn then stop, Agents loop until the goal is achieved",
      "Chatbots use Vietnamese, Agents use English",
      "Chatbots are old software, Agents are new software",
    ],
    correct: 1,
    explanation:
      "Chatbot: User hỏi → AI trả lời → Kết thúc. AI Agent: Nhận goal → Observe → Plan → Act → lặp lại cho đến khi xong. Chatbot trả lời, Agent hành động.",
    explanationEn:
      "Chatbot: User asks, AI answers, done. AI Agent: Receives goal, Observe, Plan, Act, repeat until complete. Chatbots answer; Agents take action.",
  },
  {
    id: 8,
    question:
      "Ví dụ: Claude Code nhận yêu cầu \"tạo website\" rồi tự viết code, tạo file, chạy thử, sửa bug, deploy. Đây là gì?",
    questionEn:
      "Example: Claude Code receives the request \"create a website\" then autonomously writes code, creates files, runs tests, fixes bugs, and deploys. What is this?",
    options: [
      "Chatbot — vì nó chỉ trả lời câu hỏi",
      "AI Agent — vì nó tự dùng tools và loop cho đến khi xong",
      "Super Prompt — vì nó chạy nhiều bước",
      "Meta Prompt — vì nó tự tạo prompt",
    ],
    optionsEn: [
      "Chatbot — because it only answers questions",
      "AI Agent — because it autonomously uses tools and loops until done",
      "Super Prompt — because it runs multiple steps",
      "Meta Prompt — because it creates prompts on its own",
    ],
    correct: 1,
    explanation:
      "Claude Code là AI Agent: nhận goal → tự observe (đọc code) → plan (chọn framework) → act (viết code, deploy) → loop cho đến khi hoàn thành. Ví dụ thực tế: website tranlamhuan.vn được tạo bằng cách này.",
    explanationEn:
      "Claude Code is an AI Agent: receives goal, autonomously observes (reads code), plans (chooses framework), acts (writes code, deploys), and loops until complete. Real example: the website tranlamhuan.vn was built this way.",
  },
  {
    id: 9,
    question:
      "AI Agent có thể dùng những tools nào?",
    questionEn: "What tools can an AI Agent use?",
    options: [
      "Chỉ trả lời text, không dùng tool nào",
      "Chỉ dùng được web search",
      "Search, API, code execution, file system, email...",
      "Chỉ dùng tools khi user bật từng tool một",
    ],
    optionsEn: [
      "Only responds with text, doesn't use any tools",
      "Can only use web search",
      "Search, API, code execution, file system, email...",
      "Only uses tools when the user enables them one by one",
    ],
    correct: 2,
    explanation:
      "AI Agent chủ động gọi tools: web search, API, chạy code, đọc/ghi file, gửi email... Đây là điểm khác biệt lớn nhất với chatbot — chatbot gần như không dùng tools.",
    explanationEn:
      "AI Agents proactively call tools: web search, APIs, code execution, file read/write, send emails... This is the biggest difference from chatbots — chatbots almost never use tools.",
  },
  {
    id: 10,
    question: "Câu nào SAI về Chatbot và AI Agent?",
    questionEn: "Which statement about Chatbots and AI Agents is INCORRECT?",
    options: [
      "Chatbot: user dẫn dắt flow hoàn toàn",
      "AI Agent: AI tự chọn bước tiếp theo trong phạm vi task",
      "AI Agent hoàn toàn tự quyết, không cần người giám sát",
      "Chatbot không có bộ nhớ dài hạn giữa các phiên",
    ],
    optionsEn: [
      "Chatbot: the user controls the flow entirely",
      "AI Agent: AI chooses the next step within the scope of the task",
      "AI Agent is fully autonomous and doesn't need human supervision",
      "Chatbot has no long-term memory between sessions",
    ],
    correct: 2,
    explanation:
      "AI Agent tự chọn bước tiếp theo nhưng VẪN hoạt động trong phạm vi task được giao, và vẫn cần người giám sát kết quả. Agent không phải AI tự trị hoàn toàn — nó giống nhân viên có năng lực, vẫn cần sếp review.",
    explanationEn:
      "AI Agents choose their next steps but STILL operate within the scope of the assigned task, and still need human supervision of results. An Agent is not fully autonomous AI — it's like a capable employee who still needs a manager to review their work.",
  },
];

export default function QuizBai3() {
  return (
    <QuizTemplate
      title="Bài Kiểm Tra — Bài 3"
      subtitle="Super Prompt, Meta Prompt & AI Agent"
      lessonNumber={3}
      questions={questions}
      passScore={7}
      nextLesson="Bài 4: Agentic AI & Thực Hành"
      apiEndpoint="/api/quiz-ai-bai-3"
    />
  );
}
